sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install: 
  - cd 19_RestWithAspNet5_Docker/RestWithAspNet5
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin >/dev/null 2>&1
deploy:
  provider: script
  script: 
    docker tag rest-with-aspnet-udemy:latest $DOCKER_USERNAME/rest-with-aspnet-udemy:$TRAVIS_JOB_ID;
    docker tag rest-with-aspnet5-db:latest $DOCKER_USERNAME/rest-with-aspnet5-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-aspnet-udemy:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-aspnet5-db:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email: false
